"""One page saying which market is available from which source, and where.

The survey already asks every provider what it has. Its answer went to a
thirty-day Actions artifact, so the one thing anybody actually wants -- can we
get an anytime-scorer price for every player, and from whom -- was never
written down anywhere a reader or a future run could see.

This renders that answer as tracked Markdown. It is generated, never edited by
hand: a stale hand-written table about which bookmaker covers what is worse
than no table, because it reads exactly like a current one.
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime

from fpl_andres.adapters.player_props import (
    SCORING_EVENTS,
    ProbeResult,
    PropSource,
)

__all__ = ["render_catalogue"]

#: What the console prints for a status, in a form a table can hold.
_STATUS_WORDS = {
    "ok": "answered",
    "no_credential": "no key",
    "unreachable": "blocked",
    "refused": "refused",
    "unreadable": "unreadable",
}

#: The two the projection actually needs, called what a manager calls them.
_HEADLINE_EVENTS = ("goal", "assist")


def _status(result: ProbeResult) -> str:
    word = _STATUS_WORDS.get(result.status, result.status)
    if result.http_status is None:
        return word
    return f"{word} ({result.http_status})"


def _coverage_row(source: PropSource, result: ProbeResult) -> str:
    cells = ["yes" if event in source.covers else "—" for event in SCORING_EVENTS]
    return f"| {source.name} | {_status(result)} | " + " | ".join(cells) + " |"


def _credentials(source: PropSource) -> str:
    if not source.credential_env:
        return "open"
    return ", ".join(f"`{name}`" for name in source.credential_env)


def render_catalogue(
    sources: Sequence[PropSource],
    results: Sequence[ProbeResult],
    surveyed_at: datetime,
) -> str:
    """The survey as Markdown, ready to commit."""
    if len(sources) != len(results):
        raise ValueError("every source needs exactly one result")

    answered = [source for source, result in zip(sources, results, strict=True) if result.ok]
    scoring = [
        source
        for source in answered
        if source.market and any(event in source.covers for event in _HEADLINE_EVENTS)
    ]

    lines: list[str] = [
        "# Player market catalogue",
        "",
        "Generated by `survey-player-props --catalogue`. Do not edit by hand.",
        "",
        f"Surveyed {surveyed_at.strftime('%Y-%m-%d %H:%M')} UTC. "
        f"{len(answered)} of {len(sources)} sources answered; "
        f"{len(scoring)} of those price a scoring market.",
        "",
        "## Can we price a player's chance to score?",
        "",
    ]

    if scoring:
        for source in scoring:
            lines.append(
                f"- **{source.name}** — {', '.join(source.covers)}. "
                f"Credentials: {_credentials(source)}. {source.terms}"
            )
    else:
        lines.append(
            "Not from anything that answered this run. Every source that "
            "prices a goal needs a credential this repository does not hold, "
            "or refused the request. Until one answers, the projection has no "
            "market view of a player and says so rather than inventing one."
        )
        lines.append("")
        lines.append(
            "Understat and FPL are not listed here even when they answer. One "
            "is a rate source and the other is the thing being predicted; "
            "neither is somebody with money on the outcome."
        )

    lines += [
        "",
        "## Every source, every scoring route",
        "",
        "`yes` means the provider claims to price it, not that this run saw a",
        "price. The status column is what the probe actually got.",
        "",
        "| Source | Status | " + " | ".join(SCORING_EVENTS) + " |",
        "| --- | --- |" + " --- |" * len(SCORING_EVENTS),
    ]
    lines += [
        _coverage_row(source, result) for source, result in zip(sources, results, strict=True)
    ]

    lines += ["", "## What each one said", ""]
    for source, result in zip(sources, results, strict=True):
        lines.append(f"### {source.name}")
        lines.append("")
        lines.append(f"- Home: <{source.homepage}>")
        lines.append(f"- Credentials: {_credentials(source)}")
        lines.append(f"- Terms: {source.terms}")
        lines.append(f"- Status: {_status(result)} — {result.note}")
        if result.markets:
            lines.append(f"- Markets named ({len(result.markets)}):")
            lines += [f"  - `{name}`" for name in result.markets]
        if result.fields:
            lines.append(f"- Response carried {len(result.fields)} fields.")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"
